/**
 * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 * 📦 Order Model
 * نموذج الطلبات
 * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 */

const { query } = require('../config/database');

class Order {
  
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // CREATE
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  
  static async create(orderData) {
    try {
      // Calculate total
      const amount = parseFloat(orderData.amount) || 0;
      const deliveryFee = parseFloat(orderData.delivery_fee) || 0;
      const total = amount + deliveryFee;
      
      const sql = `
        INSERT INTO orders (
          order_number, user_id, vendor_id, service_description,
          scheduled_date, scheduled_time, address, city, area, phone,
          amount, delivery_fee, total, status, notes
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `;
      
      const result = await query(sql, [
        orderData.order_number || null, // Will be generated by trigger if null
        orderData.user_id,
        orderData.vendor_id,
        orderData.service_description || null,
        orderData.scheduled_date || null,
        orderData.scheduled_time || null,
        orderData.address || null,
        orderData.city || null,
        orderData.area || null,
        orderData.phone || null,
        amount,
        deliveryFee,
        total,
        orderData.status || 'pending',
        orderData.notes || null
      ]);
      
      return await this.findById(result.insertId);
      
    } catch (error) {
      throw error;
    }
  }
  
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // READ
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  
  static async findById(id) {
    const sql = `
      SELECT o.*,
             u.name as customer_name,
             u.email as customer_email,
             u.phone as customer_phone,
             v.business_name as vendor_name,
             v.phone as vendor_phone,
             v.whatsapp as vendor_whatsapp
      FROM orders o
      LEFT JOIN users u ON o.user_id = u.id
      LEFT JOIN vendors v ON o.vendor_id = v.id
      WHERE o.id = ?
    `;
    
    const results = await query(sql, [id]);
    return results[0] || null;
  }
  
  static async findByOrderNumber(orderNumber) {
    const sql = `
      SELECT o.*,
             u.name as customer_name,
             u.email as customer_email,
             v.business_name as vendor_name
      FROM orders o
      LEFT JOIN users u ON o.user_id = u.id
      LEFT JOIN vendors v ON o.vendor_id = v.id
      WHERE o.order_number = ?
    `;
    
    const results = await query(sql, [orderNumber]);
    return results[0] || null;
  }
  
  /**
   * Get all orders with filters
   */
  static async getAll(filters = {}) {
    let sql = `
      SELECT o.*,
             u.name as customer_name,
             u.phone as customer_phone,
             v.business_name as vendor_name
      FROM orders o
      LEFT JOIN users u ON o.user_id = u.id
      LEFT JOIN vendors v ON o.vendor_id = v.id
      WHERE 1=1
    `;
    
    const params = [];
    
    // Filters
    if (filters.user_id) {
      sql += ' AND o.user_id = ?';
      params.push(filters.user_id);
    }
    
    if (filters.vendor_id) {
      sql += ' AND o.vendor_id = ?';
      params.push(filters.vendor_id);
    }
    
    if (filters.status) {
      sql += ' AND o.status = ?';
      params.push(filters.status);
    }
    
    if (filters.search) {
      sql += ' AND (o.order_number LIKE ? OR u.name LIKE ? OR v.business_name LIKE ?)';
      const searchTerm = `%${filters.search}%`;
      params.push(searchTerm, searchTerm, searchTerm);
    }
    
    if (filters.date_from) {
      sql += ' AND o.created_at >= ?';
      params.push(filters.date_from);
    }
    
    if (filters.date_to) {
      sql += ' AND o.created_at <= ?';
      params.push(filters.date_to);
    }
    
    if (filters.scheduled_date) {
      sql += ' AND o.scheduled_date = ?';
      params.push(filters.scheduled_date);
    }
    
    // Sorting
    const sortBy = filters.sort || 'created_at';
    const sortOrder = filters.order || 'DESC';
    sql += ` ORDER BY o.${sortBy} ${sortOrder}`;
    
    // Pagination
    const page = parseInt(filters.page) || 1;
    const limit = parseInt(filters.limit) || 20;
    const offset = (page - 1) * limit;
    
    sql += ' LIMIT ? OFFSET ?';
    params.push(limit, offset);
    
    const results = await query(sql, params);
    
    // Get total count
    let countSql = 'SELECT COUNT(*) as total FROM orders WHERE 1=1';
    const countParams = [];
    
    if (filters.user_id) {
      countSql += ' AND user_id = ?';
      countParams.push(filters.user_id);
    }
    
    if (filters.vendor_id) {
      countSql += ' AND vendor_id = ?';
      countParams.push(filters.vendor_id);
    }
    
    if (filters.status) {
      countSql += ' AND status = ?';
      countParams.push(filters.status);
    }
    
    const countResult = await query(countSql, countParams);
    const total = countResult[0].total;
    
    return {
      orders: results,
      pagination: {
        page,
        limit,
        total,
        totalPages: Math.ceil(total / limit)
      }
    };
  }
  
  /**
   * Get user orders
   */
  static async getUserOrders(userId, filters = {}) {
    filters.user_id = userId;
    return await this.getAll(filters);
  }
  
  /**
   * Get vendor orders
   */
  static async getVendorOrders(vendorId, filters = {}) {
    filters.vendor_id = vendorId;
    return await this.getAll(filters);
  }
  
  /**
   * Get pending orders
   */
  static async getPendingOrders(vendorId = null) {
    let sql = `
      SELECT o.*,
             u.name as customer_name,
             u.phone as customer_phone,
             v.business_name as vendor_name
      FROM orders o
      LEFT JOIN users u ON o.user_id = u.id
      LEFT JOIN vendors v ON o.vendor_id = v.id
      WHERE o.status = 'pending'
    `;
    
    const params = [];
    
    if (vendorId) {
      sql += ' AND o.vendor_id = ?';
      params.push(vendorId);
    }
    
    sql += ' ORDER BY o.created_at DESC';
    
    return await query(sql, params);
  }
  
  /**
   * Get upcoming orders (scheduled for future)
   */
  static async getUpcomingOrders(userId = null, vendorId = null) {
    let sql = `
      SELECT o.*,
             u.name as customer_name,
             v.business_name as vendor_name
      FROM orders o
      LEFT JOIN users u ON o.user_id = u.id
      LEFT JOIN vendors v ON o.vendor_id = v.id
      WHERE o.status IN ('confirmed', 'in_progress')
        AND o.scheduled_date >= CURDATE()
    `;
    
    const params = [];
    
    if (userId) {
      sql += ' AND o.user_id = ?';
      params.push(userId);
    }
    
    if (vendorId) {
      sql += ' AND o.vendor_id = ?';
      params.push(vendorId);
    }
    
    sql += ' ORDER BY o.scheduled_date ASC, o.scheduled_time ASC';
    
    return await query(sql, params);
  }
  
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // UPDATE
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  
  static async update(id, orderData) {
    const allowedFields = [
      'service_description', 'scheduled_date', 'scheduled_time',
      'address', 'city', 'area', 'phone', 'amount', 'delivery_fee', 'notes'
    ];
    
    const updates = [];
    const params = [];
    
    for (const field of allowedFields) {
      if (orderData[field] !== undefined) {
        updates.push(`${field} = ?`);
        params.push(orderData[field]);
      }
    }
    
    // Recalculate total if amount or delivery_fee changed
    if (orderData.amount !== undefined || orderData.delivery_fee !== undefined) {
      const currentOrder = await this.findById(id);
      const amount = orderData.amount !== undefined ? 
        parseFloat(orderData.amount) : parseFloat(currentOrder.amount);
      const deliveryFee = orderData.delivery_fee !== undefined ? 
        parseFloat(orderData.delivery_fee) : parseFloat(currentOrder.delivery_fee);
      
      updates.push('total = ?');
      params.push(amount + deliveryFee);
    }
    
    if (updates.length === 0) {
      throw new Error('لا توجد بيانات للتحديث');
    }
    
    params.push(id);
    
    const sql = `
      UPDATE orders
      SET ${updates.join(', ')}, updated_at = CURRENT_TIMESTAMP
      WHERE id = ?
    `;
    
    await query(sql, params);
    return await this.findById(id);
  }
  
  /**
   * Update order status
   */
  static async updateStatus(id, status, vendorNotes = null) {
    const validStatuses = ['pending', 'confirmed', 'in_progress', 'completed', 'cancelled'];
    
    if (!validStatuses.includes(status)) {
      throw new Error('حالة الطلب غير صحيحة');
    }
    
    let sql = `
      UPDATE orders
      SET status = ?, updated_at = CURRENT_TIMESTAMP
    `;
    
    const params = [status];
    
    if (vendorNotes) {
      sql += ', vendor_notes = ?';
      params.push(vendorNotes);
    }
    
    if (status === 'completed') {
      sql += ', completed_at = CURRENT_TIMESTAMP';
    }
    
    sql += ' WHERE id = ?';
    params.push(id);
    
    await query(sql, params);
    return await this.findById(id);
  }
  
  /**
   * Confirm order
   */
  static async confirm(id, vendorNotes = null) {
    return await this.updateStatus(id, 'confirmed', vendorNotes);
  }
  
  /**
   * Start order (in progress)
   */
  static async startProgress(id, vendorNotes = null) {
    return await this.updateStatus(id, 'in_progress', vendorNotes);
  }
  
  /**
   * Complete order
   */
  static async complete(id, vendorNotes = null) {
    const order = await this.updateStatus(id, 'completed', vendorNotes);
    
    // Increment vendor total_orders
    await query(
      'UPDATE vendors SET total_orders = total_orders + 1 WHERE id = ?',
      [order.vendor_id]
    );
    
    return order;
  }
  
  /**
   * Cancel order
   */
  static async cancel(id, cancellationReason) {
    const sql = `
      UPDATE orders
      SET status = 'cancelled',
          cancellation_reason = ?,
          updated_at = CURRENT_TIMESTAMP
      WHERE id = ?
    `;
    
    await query(sql, [cancellationReason, id]);
    return await this.findById(id);
  }
  
  /**
   * Add vendor notes
   */
  static async addVendorNotes(id, notes) {
    const sql = `
      UPDATE orders
      SET vendor_notes = ?, updated_at = CURRENT_TIMESTAMP
      WHERE id = ?
    `;
    
    await query(sql, [notes, id]);
    return await this.findById(id);
  }
  
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // DELETE
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  
  static async delete(id) {
    // Only allow deletion of cancelled or pending orders
    const order = await this.findById(id);
    
    if (!order) {
      throw new Error('الطلب غير موجود');
    }
    
    if (!['cancelled', 'pending'].includes(order.status)) {
      throw new Error('لا يمكن حذف طلب نشط');
    }
    
    const sql = 'DELETE FROM orders WHERE id = ?';
    await query(sql, [id]);
    return true;
  }
  
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // STATISTICS
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  
  /**
   * Get user order statistics
   */
  static async getUserStats(userId) {
    const sql = `
      SELECT 
        COUNT(*) as total_orders,
        SUM(CASE WHEN status = 'pending' THEN 1 ELSE 0 END) as pending,
        SUM(CASE WHEN status = 'confirmed' THEN 1 ELSE 0 END) as confirmed,
        SUM(CASE WHEN status = 'in_progress' THEN 1 ELSE 0 END) as in_progress,
        SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END) as completed,
        SUM(CASE WHEN status = 'cancelled' THEN 1 ELSE 0 END) as cancelled,
        SUM(CASE WHEN status = 'completed' THEN total ELSE 0 END) as total_spent
      FROM orders
      WHERE user_id = ?
    `;
    
    const result = await query(sql, [userId]);
    return result[0];
  }
  
  /**
   * Get vendor order statistics
   */
  static async getVendorStats(vendorId) {
    const sql = `
      SELECT 
        COUNT(*) as total_orders,
        SUM(CASE WHEN status = 'pending' THEN 1 ELSE 0 END) as pending,
        SUM(CASE WHEN status = 'confirmed' THEN 1 ELSE 0 END) as confirmed,
        SUM(CASE WHEN status = 'in_progress' THEN 1 ELSE 0 END) as in_progress,
        SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END) as completed,
        SUM(CASE WHEN status = 'cancelled' THEN 1 ELSE 0 END) as cancelled,
        SUM(CASE WHEN status = 'completed' THEN total ELSE 0 END) as total_revenue,
        AVG(CASE WHEN status = 'completed' THEN total ELSE NULL END) as average_order_value
      FROM orders
      WHERE vendor_id = ?
    `;
    
    const result = await query(sql, [vendorId]);
    return result[0];
  }
  
  /**
   * Get overall statistics
   */
  static async getOverallStats() {
    const sql = `
      SELECT 
        COUNT(*) as total_orders,
        SUM(CASE WHEN status = 'pending' THEN 1 ELSE 0 END) as pending,
        SUM(CASE WHEN status = 'confirmed' THEN 1 ELSE 0 END) as confirmed,
        SUM(CASE WHEN status = 'in_progress' THEN 1 ELSE 0 END) as in_progress,
        SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END) as completed,
        SUM(CASE WHEN status = 'cancelled' THEN 1 ELSE 0 END) as cancelled,
        SUM(total) as total_value,
        AVG(total) as average_order_value
      FROM orders
    `;
    
    const result = await query(sql);
    return result[0];
  }
  
  /**
   * Get daily revenue for a vendor
   */
  static async getDailyRevenue(vendorId, days = 30) {
    const sql = `
      SELECT 
        DATE(created_at) as date,
        COUNT(*) as order_count,
        SUM(total) as revenue
      FROM orders
      WHERE vendor_id = ? 
        AND status = 'completed'
        AND created_at >= DATE_SUB(CURDATE(), INTERVAL ? DAY)
      GROUP BY DATE(created_at)
      ORDER BY date DESC
    `;
    
    return await query(sql, [vendorId, days]);
  }
  
  /**
   * Get monthly revenue for a vendor
   */
  static async getMonthlyRevenue(vendorId, months = 12) {
    const sql = `
      SELECT 
        DATE_FORMAT(created_at, '%Y-%m') as month,
        COUNT(*) as order_count,
        SUM(total) as revenue
      FROM orders
      WHERE vendor_id = ? 
        AND status = 'completed'
        AND created_at >= DATE_SUB(CURDATE(), INTERVAL ? MONTH)
      GROUP BY DATE_FORMAT(created_at, '%Y-%m')
      ORDER BY month DESC
    `;
    
    return await query(sql, [vendorId, months]);
  }
}

module.exports = Order;
